export const LEAGUE_STANDING = {
  "code": 0,
  "message": "success",
  "data": {
    "leagueInfo": {
      "leagueId": "1639",
      "name": "English Premier League",
      "shortName": "ENG PR",
      "logo": "http://zq.titan007.com/image/league_match/images/164577482086.png?win007=sell",
      "color": "#FF3333",
      "totalRound": 38,
      "currentRound": 37,
      "currentSeason": "2023-2024"
    },
    "subLeagueInfos": [],
    "teamInfos": [
      {
        "teamId": "19",
        "name": "Arsenal",
        "logo": "http://zq.titan007.com/image/team/images/164577419697.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "20",
        "name": "Aston Villa",
        "logo": "http://zq.titan007.com/image/team/images/1ht23n9jnb30.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "24",
        "name": "Chelsea",
        "logo": "http://zq.titan007.com/image/team/images/164577409120.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "25",
        "name": "Liverpool",
        "logo": "http://zq.titan007.com/image/team/images/164577447430.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "26",
        "name": "Manchester City",
        "logo": "http://zq.titan007.com/image/team/images/164577478031.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "27",
        "name": "Manchester United",
        "logo": "http://zq.titan007.com/image/team/images/164577479190.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "28",
        "name": "Newcastle United",
        "logo": "http://zq.titan007.com/image/team/images/164577474623.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "29",
        "name": "Fulham",
        "logo": "http://zq.titan007.com/image/team/images/16486909637.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "31",
        "name": "Everton",
        "logo": "http://zq.titan007.com/image/team/images/164577449385.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "33",
        "name": "Tottenham Hotspur",
        "logo": "http://zq.titan007.com/image/team/images/33/1h746a4jfr1p.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "35",
        "name": "Crystal Palace",
        "logo": "http://zq.titan007.com/image/team/images/164577426766.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "46",
        "name": "Burnley",
        "logo": "http://zq.titan007.com/image/team/images/1h99zdamy01a.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "49",
        "name": "Nottingham Forest",
        "logo": "http://zq.titan007.com/image/team/images/164869100556.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "51",
        "name": "Sheffield United",
        "logo": "http://zq.titan007.com/image/team/images/164869103617.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "52",
        "name": "Wolves",
        "logo": "http://zq.titan007.com/image/team/images/164577451783.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "60",
        "name": "Brighton Hove Albion",
        "logo": "http://zq.titan007.com/image/team/images/164577420829.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "62",
        "name": "West Ham United",
        "logo": "http://zq.titan007.com/image/team/images/164577453830.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "348",
        "name": "AFC Bournemouth",
        "logo": "http://zq.titan007.com/image/team/images/164869115455.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "365",
        "name": "Brentford",
        "logo": "http://zq.titan007.com/image/team/images/164601812119.png?win007=sell",
        "area": 0
      },
      {
        "teamId": "372",
        "name": "Luton Town",
        "logo": "http://zq.titan007.com/image/team/images/164869119739.png?win007=sell",
        "area": 0
      }
    ],
    "totalStandings": [
      {
        "rank": 1,
        "teamId": "19",
        "winRate": "73.0",
        "drawRate": "13.5",
        "loseRate": "13.5",
        "winAverage": "2.41",
        "loseAverage": "0.76",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 2,
        "recentSecondResult": 0,
        "recentThirdResult": 0,
        "recentFourthResult": 0,
        "recentFifthResult": 0,
        "recentSixthResult": 0,
        "color": "0",
        "red": 2,
        "totalCount": 37,
        "winCount": 27,
        "drawCount": 5,
        "loseCount": 5,
        "getScore": 92,
        "loseScore": 28,
        "goalDifference": 61,
        "totalAddScore": 0,
        "integral": 86
      },
      {
        "rank": 2,
        "teamId": "26",
        "winRate": "72.2",
        "drawRate": "19.4",
        "loseRate": "8.3",
        "winAverage": "2.53",
        "loseAverage": "0.92",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 0,
        "recentSecondResult": 0,
        "recentThirdResult": 0,
        "recentFourthResult": 0,
        "recentFifthResult": 0,
        "recentSixthResult": 0,
        "color": "0",
        "red": 2,
        "totalCount": 36,
        "winCount": 26,
        "drawCount": 7,
        "loseCount": 3,
        "getScore": 91,
        "loseScore": 33,
        "goalDifference": 58,
        "totalAddScore": 0,
        "integral": 85
      },
      {
        "rank": 3,
        "teamId": "25",
        "winRate": "63.9",
        "drawRate": "25.0",
        "loseRate": "11.1",
        "winAverage": "2.25",
        "loseAverage": "1.06",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 1,
        "recentSecondResult": 2,
        "recentThirdResult": 0,
        "recentFourthResult": 2,
        "recentFifthResult": 1,
        "recentSixthResult": 0,
        "color": "0",
        "red": 5,
        "totalCount": 36,
        "winCount": 23,
        "drawCount": 9,
        "loseCount": 4,
        "getScore": 81,
        "loseScore": 38,
        "goalDifference": 43,
        "totalAddScore": 0,
        "integral": 78
      },
      {
        "rank": 4,
        "teamId": "20",
        "winRate": "55.6",
        "drawRate": "19.4",
        "loseRate": "25.0",
        "winAverage": "2.03",
        "loseAverage": "1.47",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 2,
        "recentSecondResult": 1,
        "recentThirdResult": 0,
        "recentFourthResult": 0,
        "recentFifthResult": 1,
        "recentSixthResult": 2,
        "color": "0",
        "red": 2,
        "totalCount": 36,
        "winCount": 20,
        "drawCount": 7,
        "loseCount": 9,
        "getScore": 73,
        "loseScore": 53,
        "goalDifference": 20,
        "totalAddScore": 0,
        "integral": 67
      },
      {
        "rank": 5,
        "teamId": "33",
        "winRate": "52.8",
        "drawRate": "16.7",
        "loseRate": "30.6",
        "winAverage": "1.97",
        "loseAverage": "1.64",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 0,
        "recentSecondResult": 2,
        "recentThirdResult": 2,
        "recentFourthResult": 2,
        "recentFifthResult": 2,
        "recentSixthResult": 0,
        "color": "1",
        "red": 4,
        "totalCount": 36,
        "winCount": 19,
        "drawCount": 6,
        "loseCount": 11,
        "getScore": 71,
        "loseScore": 59,
        "goalDifference": 12,
        "totalAddScore": 0,
        "integral": 63
      },
      {
        "rank": 6,
        "teamId": "28",
        "winRate": "47.2",
        "drawRate": "16.7",
        "loseRate": "36.1",
        "winAverage": "2.19",
        "loseAverage": "1.58",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 0,
        "recentSecondResult": 0,
        "recentThirdResult": 2,
        "recentFourthResult": 0,
        "recentFifthResult": 0,
        "recentSixthResult": 1,
        "color": "2",
        "red": 1,
        "totalCount": 36,
        "winCount": 17,
        "drawCount": 6,
        "loseCount": 13,
        "getScore": 79,
        "loseScore": 57,
        "goalDifference": 22,
        "totalAddScore": 0,
        "integral": 57
      },
      {
        "rank": 7,
        "teamId": "24",
        "winRate": "44.4",
        "drawRate": "25.0",
        "loseRate": "30.6",
        "winAverage": "2.03",
        "loseAverage": "1.69",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 0,
        "recentSecondResult": 2,
        "recentThirdResult": 1,
        "recentFourthResult": 0,
        "recentFifthResult": 0,
        "recentSixthResult": 0,
        "color": "-1",
        "red": 3,
        "totalCount": 36,
        "winCount": 16,
        "drawCount": 9,
        "loseCount": 11,
        "getScore": 73,
        "loseScore": 61,
        "goalDifference": 12,
        "totalAddScore": 0,
        "integral": 57
      },
      {
        "rank": 8,
        "teamId": "27",
        "winRate": "44.4",
        "drawRate": "16.7",
        "loseRate": "38.9",
        "winAverage": "1.44",
        "loseAverage": "1.56",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 1,
        "recentSecondResult": 1,
        "recentThirdResult": 0,
        "recentFourthResult": 1,
        "recentFifthResult": 2,
        "recentSixthResult": 2,
        "color": "-1",
        "red": 1,
        "totalCount": 36,
        "winCount": 16,
        "drawCount": 6,
        "loseCount": 14,
        "getScore": 52,
        "loseScore": 56,
        "goalDifference": -4,
        "totalAddScore": 0,
        "integral": 54
      },
      {
        "rank": 9,
        "teamId": "62",
        "winRate": "37.8",
        "drawRate": "27.0",
        "loseRate": "35.1",
        "winAverage": "1.59",
        "loseAverage": "1.92",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 0,
        "recentSecondResult": 2,
        "recentThirdResult": 2,
        "recentFourthResult": 1,
        "recentFifthResult": 2,
        "recentSixthResult": 0,
        "color": "-1",
        "red": 3,
        "totalCount": 37,
        "winCount": 14,
        "drawCount": 10,
        "loseCount": 13,
        "getScore": 59,
        "loseScore": 71,
        "goalDifference": -12,
        "totalAddScore": 0,
        "integral": 52
      },
      {
        "rank": 10,
        "teamId": "60",
        "winRate": "33.3",
        "drawRate": "33.3",
        "loseRate": "33.3",
        "winAverage": "1.5",
        "loseAverage": "1.61",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 2,
        "recentSecondResult": 1,
        "recentThirdResult": 2,
        "recentFourthResult": 2,
        "recentFifthResult": 0,
        "recentSixthResult": 1,
        "color": "-1",
        "red": 3,
        "totalCount": 36,
        "winCount": 12,
        "drawCount": 12,
        "loseCount": 12,
        "getScore": 54,
        "loseScore": 58,
        "goalDifference": -4,
        "totalAddScore": 0,
        "integral": 48
      },
      {
        "rank": 11,
        "teamId": "348",
        "winRate": "35.1",
        "drawRate": "24.3",
        "loseRate": "40.5",
        "winAverage": "1.43",
        "loseAverage": "1.76",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 1,
        "recentSecondResult": 2,
        "recentThirdResult": 0,
        "recentFourthResult": 0,
        "recentFifthResult": 2,
        "recentSixthResult": 2,
        "color": "-1",
        "red": 3,
        "totalCount": 37,
        "winCount": 13,
        "drawCount": 9,
        "loseCount": 15,
        "getScore": 53,
        "loseScore": 65,
        "goalDifference": -12,
        "totalAddScore": 0,
        "integral": 48
      },
      {
        "rank": 12,
        "teamId": "35",
        "winRate": "32.4",
        "drawRate": "27.0",
        "loseRate": "40.5",
        "winAverage": "1.41",
        "loseAverage": "1.57",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 0,
        "recentSecondResult": 0,
        "recentThirdResult": 0,
        "recentFourthResult": 1,
        "recentFifthResult": 0,
        "recentSixthResult": 0,
        "color": "-1",
        "red": 2,
        "totalCount": 37,
        "winCount": 12,
        "drawCount": 10,
        "loseCount": 15,
        "getScore": 52,
        "loseScore": 58,
        "goalDifference": -6,
        "totalAddScore": 0,
        "integral": 46
      },
      {
        "rank": 13,
        "teamId": "52",
        "winRate": "35.1",
        "drawRate": "18.9",
        "loseRate": "45.9",
        "winAverage": "1.35",
        "loseAverage": "1.7",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 1,
        "recentSecondResult": 2,
        "recentThirdResult": 2,
        "recentFourthResult": 0,
        "recentFifthResult": 2,
        "recentSixthResult": 2,
        "color": "-1",
        "red": 3,
        "totalCount": 37,
        "winCount": 13,
        "drawCount": 7,
        "loseCount": 17,
        "getScore": 50,
        "loseScore": 63,
        "goalDifference": -13,
        "totalAddScore": 0,
        "integral": 46
      },
      {
        "rank": 14,
        "teamId": "29",
        "winRate": "32.4",
        "drawRate": "21.6",
        "loseRate": "45.9",
        "winAverage": "1.38",
        "loseAverage": "1.59",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 2,
        "recentSecondResult": 0,
        "recentThirdResult": 2,
        "recentFourthResult": 1,
        "recentFifthResult": 1,
        "recentSixthResult": 2,
        "color": "-1",
        "red": 4,
        "totalCount": 37,
        "winCount": 12,
        "drawCount": 8,
        "loseCount": 17,
        "getScore": 51,
        "loseScore": 59,
        "goalDifference": -8,
        "totalAddScore": 0,
        "integral": 44
      },
      {
        "rank": 15,
        "teamId": "31",
        "winRate": "35.1",
        "drawRate": "24.3",
        "loseRate": "40.5",
        "winAverage": "1.05",
        "loseAverage": "1.32",
        "deduction": "8",
        "deductionExplain": "8 points on Everton FC for a breach of the Premier League’s",
        "recentFirstResult": 2,
        "recentSecondResult": 0,
        "recentThirdResult": 0,
        "recentFourthResult": 0,
        "recentFifthResult": 1,
        "recentSixthResult": 0,
        "color": "-1",
        "red": 1,
        "totalCount": 37,
        "winCount": 13,
        "drawCount": 9,
        "loseCount": 15,
        "getScore": 39,
        "loseScore": 49,
        "goalDifference": -10,
        "totalAddScore": 0,
        "integral": 40
      },
      {
        "rank": 16,
        "teamId": "365",
        "winRate": "27.0",
        "drawRate": "24.3",
        "loseRate": "48.6",
        "winAverage": "1.46",
        "loseAverage": "1.65",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 1,
        "recentSecondResult": 0,
        "recentThirdResult": 0,
        "recentFourthResult": 2,
        "recentFifthResult": 1,
        "recentSixthResult": 0,
        "color": "-1",
        "red": 2,
        "totalCount": 37,
        "winCount": 10,
        "drawCount": 9,
        "loseCount": 18,
        "getScore": 54,
        "loseScore": 61,
        "goalDifference": -7,
        "totalAddScore": 0,
        "integral": 39
      },
      {
        "rank": 17,
        "teamId": "49",
        "winRate": "21.6",
        "drawRate": "24.3",
        "loseRate": "54.1",
        "winAverage": "1.27",
        "loseAverage": "1.78",
        "deduction": "4",
        "deductionExplain": "4 points on Nottingham  for a breach of the Premier League’s",
        "recentFirstResult": 2,
        "recentSecondResult": 1,
        "recentThirdResult": 2,
        "recentFourthResult": 2,
        "recentFifthResult": 0,
        "recentSixthResult": 2,
        "color": "-1",
        "red": 3,
        "totalCount": 37,
        "winCount": 8,
        "drawCount": 9,
        "loseCount": 20,
        "getScore": 47,
        "loseScore": 66,
        "goalDifference": -19,
        "totalAddScore": 0,
        "integral": 29
      },
      {
        "rank": 18,
        "teamId": "372",
        "winRate": "16.2",
        "drawRate": "21.6",
        "loseRate": "62.2",
        "winAverage": "1.35",
        "loseAverage": "2.19",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 0,
        "recentSecondResult": 2,
        "recentThirdResult": 2,
        "recentFourthResult": 2,
        "recentFifthResult": 1,
        "recentSixthResult": 2,
        "color": "3",
        "red": 0,
        "totalCount": 37,
        "winCount": 6,
        "drawCount": 8,
        "loseCount": 23,
        "getScore": 50,
        "loseScore": 81,
        "goalDifference": -31,
        "totalAddScore": 0,
        "integral": 26
      },
      {
        "rank": 19,
        "teamId": "46",
        "winRate": "13.5",
        "drawRate": "24.3",
        "loseRate": "62.2",
        "winAverage": "1.08",
        "loseAverage": "2.05",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 2,
        "recentSecondResult": 1,
        "recentThirdResult": 0,
        "recentFourthResult": 1,
        "recentFifthResult": 2,
        "recentSixthResult": 2,
        "color": "3",
        "red": 7,
        "totalCount": 37,
        "winCount": 5,
        "drawCount": 9,
        "loseCount": 23,
        "getScore": 40,
        "loseScore": 76,
        "goalDifference": -36,
        "totalAddScore": 0,
        "integral": 24
      },
      {
        "rank": 20,
        "teamId": "51",
        "winRate": "8.1",
        "drawRate": "18.9",
        "loseRate": "73.0",
        "winAverage": "0.95",
        "loseAverage": "2.73",
        "deduction": "0",
        "deductionExplain": "",
        "recentFirstResult": 2,
        "recentSecondResult": 2,
        "recentThirdResult": 2,
        "recentFourthResult": 2,
        "recentFifthResult": 2,
        "recentSixthResult": 2,
        "color": "3",
        "red": 5,
        "totalCount": 37,
        "winCount": 3,
        "drawCount": 7,
        "loseCount": 27,
        "getScore": 35,
        "loseScore": 101,
        "goalDifference": -66,
        "totalAddScore": 0,
        "integral": 16
      }
    ],
    "halfStandings": [
      {
        "rank": 1,
        "teamId": "19",
        "winRate": "48.6",
        "drawRate": "40.5",
        "loseRate": "10.8",
        "winAverage": "1.11",
        "loseAverage": "0.3",
        "totalCount": 37,
        "winCount": 18,
        "drawCount": 15,
        "loseCount": 4,
        "getScore": 41,
        "loseScore": 11,
        "goalDifference": 30,
        "integral": 69
      },
      {
        "rank": 2,
        "teamId": "26",
        "winRate": "55.6",
        "drawRate": "25.0",
        "loseRate": "19.4",
        "winAverage": "1.06",
        "loseAverage": "0.42",
        "totalCount": 36,
        "winCount": 20,
        "drawCount": 9,
        "loseCount": 7,
        "getScore": 38,
        "loseScore": 15,
        "goalDifference": 23,
        "integral": 69
      },
      {
        "rank": 3,
        "teamId": "20",
        "winRate": "44.4",
        "drawRate": "33.3",
        "loseRate": "22.2",
        "winAverage": "0.97",
        "loseAverage": "0.47",
        "totalCount": 36,
        "winCount": 16,
        "drawCount": 12,
        "loseCount": 8,
        "getScore": 35,
        "loseScore": 17,
        "goalDifference": 18,
        "integral": 60
      },
      {
        "rank": 4,
        "teamId": "24",
        "winRate": "33.3",
        "drawRate": "52.8",
        "loseRate": "13.9",
        "winAverage": "0.97",
        "loseAverage": "0.64",
        "totalCount": 36,
        "winCount": 12,
        "drawCount": 19,
        "loseCount": 5,
        "getScore": 35,
        "loseScore": 23,
        "goalDifference": 12,
        "integral": 55
      },
      {
        "rank": 5,
        "teamId": "28",
        "winRate": "33.3",
        "drawRate": "47.2",
        "loseRate": "19.4",
        "winAverage": "0.94",
        "loseAverage": "0.61",
        "totalCount": 36,
        "winCount": 12,
        "drawCount": 17,
        "loseCount": 7,
        "getScore": 34,
        "loseScore": 22,
        "goalDifference": 12,
        "integral": 53
      },
      {
        "rank": 6,
        "teamId": "25",
        "winRate": "33.3",
        "drawRate": "44.4",
        "loseRate": "22.2",
        "winAverage": "0.78",
        "loseAverage": "0.56",
        "totalCount": 36,
        "winCount": 12,
        "drawCount": 16,
        "loseCount": 8,
        "getScore": 28,
        "loseScore": 20,
        "goalDifference": 8,
        "integral": 52
      },
      {
        "rank": 7,
        "teamId": "35",
        "winRate": "29.7",
        "drawRate": "51.4",
        "loseRate": "18.9",
        "winAverage": "0.59",
        "loseAverage": "0.51",
        "totalCount": 37,
        "winCount": 11,
        "drawCount": 19,
        "loseCount": 7,
        "getScore": 22,
        "loseScore": 19,
        "goalDifference": 3,
        "integral": 52
      },
      {
        "rank": 8,
        "teamId": "62",
        "winRate": "35.1",
        "drawRate": "29.7",
        "loseRate": "35.1",
        "winAverage": "0.65",
        "loseAverage": "0.86",
        "totalCount": 37,
        "winCount": 13,
        "drawCount": 11,
        "loseCount": 13,
        "getScore": 24,
        "loseScore": 32,
        "goalDifference": -8,
        "integral": 50
      },
      {
        "rank": 9,
        "teamId": "60",
        "winRate": "33.3",
        "drawRate": "30.6",
        "loseRate": "36.1",
        "winAverage": "0.64",
        "loseAverage": "0.78",
        "totalCount": 36,
        "winCount": 12,
        "drawCount": 11,
        "loseCount": 13,
        "getScore": 23,
        "loseScore": 28,
        "goalDifference": -5,
        "integral": 47
      },
      {
        "rank": 10,
        "teamId": "348",
        "winRate": "27.0",
        "drawRate": "43.2",
        "loseRate": "29.7",
        "winAverage": "0.51",
        "loseAverage": "0.7",
        "totalCount": 37,
        "winCount": 10,
        "drawCount": 16,
        "loseCount": 11,
        "getScore": 19,
        "loseScore": 26,
        "goalDifference": -7,
        "integral": 46
      },
      {
        "rank": 11,
        "teamId": "33",
        "winRate": "27.8",
        "drawRate": "38.9",
        "loseRate": "33.3",
        "winAverage": "0.69",
        "loseAverage": "0.83",
        "totalCount": 36,
        "winCount": 10,
        "drawCount": 14,
        "loseCount": 12,
        "getScore": 25,
        "loseScore": 30,
        "goalDifference": -5,
        "integral": 44
      },
      {
        "rank": 12,
        "teamId": "27",
        "winRate": "25.0",
        "drawRate": "44.4",
        "loseRate": "30.6",
        "winAverage": "0.58",
        "loseAverage": "0.64",
        "totalCount": 36,
        "winCount": 9,
        "drawCount": 16,
        "loseCount": 11,
        "getScore": 21,
        "loseScore": 23,
        "goalDifference": -2,
        "integral": 43
      },
      {
        "rank": 13,
        "teamId": "365",
        "winRate": "21.6",
        "drawRate": "51.4",
        "loseRate": "27.0",
        "winAverage": "0.57",
        "loseAverage": "0.62",
        "totalCount": 37,
        "winCount": 8,
        "drawCount": 19,
        "loseCount": 10,
        "getScore": 21,
        "loseScore": 23,
        "goalDifference": -2,
        "integral": 43
      },
      {
        "rank": 14,
        "teamId": "31",
        "winRate": "21.6",
        "drawRate": "51.4",
        "loseRate": "27.0",
        "winAverage": "0.43",
        "loseAverage": "0.59",
        "totalCount": 37,
        "winCount": 8,
        "drawCount": 19,
        "loseCount": 10,
        "getScore": 16,
        "loseScore": 22,
        "goalDifference": -6,
        "integral": 43
      },
      {
        "rank": 15,
        "teamId": "52",
        "winRate": "27.0",
        "drawRate": "35.1",
        "loseRate": "37.8",
        "winAverage": "0.49",
        "loseAverage": "0.76",
        "totalCount": 37,
        "winCount": 10,
        "drawCount": 13,
        "loseCount": 14,
        "getScore": 18,
        "loseScore": 28,
        "goalDifference": -10,
        "integral": 43
      },
      {
        "rank": 16,
        "teamId": "29",
        "winRate": "21.6",
        "drawRate": "48.6",
        "loseRate": "29.7",
        "winAverage": "0.54",
        "loseAverage": "0.57",
        "totalCount": 37,
        "winCount": 8,
        "drawCount": 18,
        "loseCount": 11,
        "getScore": 20,
        "loseScore": 21,
        "goalDifference": -1,
        "integral": 42
      },
      {
        "rank": 17,
        "teamId": "372",
        "winRate": "24.3",
        "drawRate": "29.7",
        "loseRate": "45.9",
        "winAverage": "0.51",
        "loseAverage": "0.76",
        "totalCount": 37,
        "winCount": 9,
        "drawCount": 11,
        "loseCount": 17,
        "getScore": 19,
        "loseScore": 28,
        "goalDifference": -9,
        "integral": 38
      },
      {
        "rank": 18,
        "teamId": "49",
        "winRate": "16.2",
        "drawRate": "51.4",
        "loseRate": "32.4",
        "winAverage": "0.59",
        "loseAverage": "0.84",
        "totalCount": 37,
        "winCount": 6,
        "drawCount": 19,
        "loseCount": 12,
        "getScore": 22,
        "loseScore": 31,
        "goalDifference": -9,
        "integral": 37
      },
      {
        "rank": 19,
        "teamId": "46",
        "winRate": "21.6",
        "drawRate": "27.0",
        "loseRate": "51.4",
        "winAverage": "0.49",
        "loseAverage": "0.92",
        "totalCount": 37,
        "winCount": 8,
        "drawCount": 10,
        "loseCount": 19,
        "getScore": 18,
        "loseScore": 34,
        "goalDifference": -16,
        "integral": 34
      },
      {
        "rank": 20,
        "teamId": "51",
        "winRate": "10.8",
        "drawRate": "43.2",
        "loseRate": "45.9",
        "winAverage": "0.38",
        "loseAverage": "1.08",
        "totalCount": 37,
        "winCount": 4,
        "drawCount": 16,
        "loseCount": 17,
        "getScore": 14,
        "loseScore": 40,
        "goalDifference": -26,
        "integral": 28
      }
    ],
    "homeStandings": [
      {
        "rank": 1,
        "teamId": "25",
        "winRate": "77.8",
        "drawRate": "16.7",
        "loseRate": "5.6",
        "winAverage": "2.61",
        "loseAverage": "0.94",
        "totalCount": 18,
        "winCount": 14,
        "drawCount": 3,
        "loseCount": 1,
        "getScore": 47,
        "loseScore": 17,
        "goalDifference": 30,
        "integral": 45
      },
      {
        "rank": 2,
        "teamId": "26",
        "winRate": "72.2",
        "drawRate": "27.8",
        "loseRate": "0.0",
        "winAverage": "2.67",
        "loseAverage": "0.83",
        "totalCount": 18,
        "winCount": 13,
        "drawCount": 5,
        "loseCount": 0,
        "getScore": 48,
        "loseScore": 15,
        "goalDifference": 33,
        "integral": 44
      },
      {
        "rank": 3,
        "teamId": "19",
        "winRate": "77.8",
        "drawRate": "11.1",
        "loseRate": "11.1",
        "winAverage": "2.56",
        "loseAverage": "0.83",
        "totalCount": 18,
        "winCount": 14,
        "drawCount": 2,
        "loseCount": 2,
        "getScore": 46,
        "loseScore": 15,
        "goalDifference": 31,
        "integral": 44
      },
      {
        "rank": 4,
        "teamId": "28",
        "winRate": "63.2",
        "drawRate": "21.1",
        "loseRate": "15.8",
        "winAverage": "2.58",
        "loseAverage": "1.16",
        "totalCount": 19,
        "winCount": 12,
        "drawCount": 4,
        "loseCount": 3,
        "getScore": 49,
        "loseScore": 22,
        "goalDifference": 27,
        "integral": 40
      },
      {
        "rank": 5,
        "teamId": "20",
        "winRate": "66.7",
        "drawRate": "16.7",
        "loseRate": "16.7",
        "winAverage": "2.5",
        "loseAverage": "1.39",
        "totalCount": 18,
        "winCount": 12,
        "drawCount": 3,
        "loseCount": 3,
        "getScore": 45,
        "loseScore": 25,
        "goalDifference": 20,
        "integral": 39
      },
      {
        "rank": 6,
        "teamId": "33",
        "winRate": "72.2",
        "drawRate": "0.0",
        "loseRate": "27.8",
        "winAverage": "2.11",
        "loseAverage": "1.39",
        "totalCount": 18,
        "winCount": 13,
        "drawCount": 0,
        "loseCount": 5,
        "getScore": 38,
        "loseScore": 25,
        "goalDifference": 13,
        "integral": 39
      },
      {
        "rank": 7,
        "teamId": "24",
        "winRate": "55.6",
        "drawRate": "22.2",
        "loseRate": "22.2",
        "winAverage": "2.33",
        "loseAverage": "1.39",
        "totalCount": 18,
        "winCount": 10,
        "drawCount": 4,
        "loseCount": 4,
        "getScore": 42,
        "loseScore": 25,
        "goalDifference": 17,
        "integral": 34
      },
      {
        "rank": 8,
        "teamId": "60",
        "winRate": "47.1",
        "drawRate": "35.3",
        "loseRate": "17.6",
        "winAverage": "1.71",
        "loseAverage": "1.35",
        "totalCount": 17,
        "winCount": 8,
        "drawCount": 6,
        "loseCount": 3,
        "getScore": 29,
        "loseScore": 23,
        "goalDifference": 6,
        "integral": 30
      },
      {
        "rank": 9,
        "teamId": "27",
        "winRate": "50.0",
        "drawRate": "16.7",
        "loseRate": "33.3",
        "winAverage": "1.56",
        "loseAverage": "1.44",
        "totalCount": 18,
        "winCount": 9,
        "drawCount": 3,
        "loseCount": 6,
        "getScore": 28,
        "loseScore": 26,
        "goalDifference": 2,
        "integral": 30
      },
      {
        "rank": 10,
        "teamId": "29",
        "winRate": "47.4",
        "drawRate": "10.5",
        "loseRate": "42.1",
        "winAverage": "1.63",
        "loseAverage": "1.26",
        "totalCount": 19,
        "winCount": 9,
        "drawCount": 2,
        "loseCount": 8,
        "getScore": 31,
        "loseScore": 24,
        "goalDifference": 7,
        "integral": 29
      },
      {
        "rank": 11,
        "teamId": "62",
        "winRate": "36.8",
        "drawRate": "42.1",
        "loseRate": "21.1",
        "winAverage": "1.63",
        "loseAverage": "1.47",
        "totalCount": 19,
        "winCount": 7,
        "drawCount": 8,
        "loseCount": 4,
        "getScore": 31,
        "loseScore": 28,
        "goalDifference": 3,
        "integral": 29
      },
      {
        "rank": 12,
        "teamId": "31",
        "winRate": "42.1",
        "drawRate": "21.1",
        "loseRate": "36.8",
        "winAverage": "1.16",
        "loseAverage": "0.95",
        "totalCount": 19,
        "winCount": 8,
        "drawCount": 4,
        "loseCount": 7,
        "getScore": 22,
        "loseScore": 18,
        "goalDifference": 4,
        "integral": 28
      },
      {
        "rank": 13,
        "teamId": "348",
        "winRate": "36.8",
        "drawRate": "31.6",
        "loseRate": "31.6",
        "winAverage": "1.42",
        "loseAverage": "1.47",
        "totalCount": 19,
        "winCount": 7,
        "drawCount": 6,
        "loseCount": 6,
        "getScore": 27,
        "loseScore": 28,
        "goalDifference": -1,
        "integral": 27
      },
      {
        "rank": 14,
        "teamId": "52",
        "winRate": "42.1",
        "drawRate": "15.8",
        "loseRate": "42.1",
        "winAverage": "1.37",
        "loseAverage": "1.58",
        "totalCount": 19,
        "winCount": 8,
        "drawCount": 3,
        "loseCount": 8,
        "getScore": 26,
        "loseScore": 30,
        "goalDifference": -4,
        "integral": 27
      },
      {
        "rank": 15,
        "teamId": "35",
        "winRate": "38.9",
        "drawRate": "22.2",
        "loseRate": "38.9",
        "winAverage": "1.78",
        "loseAverage": "1.44",
        "totalCount": 18,
        "winCount": 7,
        "drawCount": 4,
        "loseCount": 7,
        "getScore": 32,
        "loseScore": 26,
        "goalDifference": 6,
        "integral": 25
      },
      {
        "rank": 16,
        "teamId": "365",
        "winRate": "27.8",
        "drawRate": "38.9",
        "loseRate": "33.3",
        "winAverage": "1.5",
        "loseAverage": "1.67",
        "totalCount": 18,
        "winCount": 5,
        "drawCount": 7,
        "loseCount": 6,
        "getScore": 27,
        "loseScore": 30,
        "goalDifference": -3,
        "integral": 22
      },
      {
        "rank": 17,
        "teamId": "49",
        "winRate": "26.3",
        "drawRate": "26.3",
        "loseRate": "47.4",
        "winAverage": "1.42",
        "loseAverage": "1.58",
        "totalCount": 19,
        "winCount": 5,
        "drawCount": 5,
        "loseCount": 9,
        "getScore": 27,
        "loseScore": 30,
        "goalDifference": -3,
        "integral": 20
      },
      {
        "rank": 18,
        "teamId": "372",
        "winRate": "22.2",
        "drawRate": "22.2",
        "loseRate": "55.6",
        "winAverage": "1.44",
        "loseAverage": "1.83",
        "totalCount": 18,
        "winCount": 4,
        "drawCount": 4,
        "loseCount": 10,
        "getScore": 26,
        "loseScore": 33,
        "goalDifference": -7,
        "integral": 16
      },
      {
        "rank": 19,
        "teamId": "46",
        "winRate": "11.1",
        "drawRate": "22.2",
        "loseRate": "66.7",
        "winAverage": "1.0",
        "loseAverage": "2.28",
        "totalCount": 18,
        "winCount": 2,
        "drawCount": 4,
        "loseCount": 12,
        "getScore": 18,
        "loseScore": 41,
        "goalDifference": -23,
        "integral": 10
      },
      {
        "rank": 20,
        "teamId": "51",
        "winRate": "11.1",
        "drawRate": "22.2",
        "loseRate": "66.7",
        "winAverage": "1.06",
        "loseAverage": "3.0",
        "totalCount": 18,
        "winCount": 2,
        "drawCount": 4,
        "loseCount": 12,
        "getScore": 19,
        "loseScore": 54,
        "goalDifference": -35,
        "integral": 10
      }
    ],
    "awayStandings": [
      {
        "rank": 1,
        "teamId": "19",
        "winRate": "68.4",
        "drawRate": "15.8",
        "loseRate": "15.8",
        "winAverage": "2.26",
        "loseAverage": "0.68",
        "totalCount": 19,
        "winCount": 13,
        "drawCount": 3,
        "loseCount": 3,
        "getScore": 43,
        "loseScore": 13,
        "goalDifference": 30,
        "integral": 42
      },
      {
        "rank": 2,
        "teamId": "26",
        "winRate": "72.2",
        "drawRate": "11.1",
        "loseRate": "16.7",
        "winAverage": "2.39",
        "loseAverage": "1.0",
        "totalCount": 18,
        "winCount": 13,
        "drawCount": 2,
        "loseCount": 3,
        "getScore": 43,
        "loseScore": 18,
        "goalDifference": 25,
        "integral": 41
      },
      {
        "rank": 3,
        "teamId": "25",
        "winRate": "50.0",
        "drawRate": "33.3",
        "loseRate": "16.7",
        "winAverage": "1.89",
        "loseAverage": "1.17",
        "totalCount": 18,
        "winCount": 9,
        "drawCount": 6,
        "loseCount": 3,
        "getScore": 34,
        "loseScore": 21,
        "goalDifference": 13,
        "integral": 33
      },
      {
        "rank": 4,
        "teamId": "20",
        "winRate": "44.4",
        "drawRate": "22.2",
        "loseRate": "33.3",
        "winAverage": "1.56",
        "loseAverage": "1.56",
        "totalCount": 18,
        "winCount": 8,
        "drawCount": 4,
        "loseCount": 6,
        "getScore": 28,
        "loseScore": 28,
        "goalDifference": 0,
        "integral": 28
      },
      {
        "rank": 5,
        "teamId": "33",
        "winRate": "33.3",
        "drawRate": "33.3",
        "loseRate": "33.3",
        "winAverage": "1.83",
        "loseAverage": "1.89",
        "totalCount": 18,
        "winCount": 6,
        "drawCount": 6,
        "loseCount": 6,
        "getScore": 33,
        "loseScore": 34,
        "goalDifference": -1,
        "integral": 24
      },
      {
        "rank": 6,
        "teamId": "27",
        "winRate": "38.9",
        "drawRate": "16.7",
        "loseRate": "44.4",
        "winAverage": "1.33",
        "loseAverage": "1.67",
        "totalCount": 18,
        "winCount": 7,
        "drawCount": 3,
        "loseCount": 8,
        "getScore": 24,
        "loseScore": 30,
        "goalDifference": -6,
        "integral": 24
      },
      {
        "rank": 7,
        "teamId": "24",
        "winRate": "33.3",
        "drawRate": "27.8",
        "loseRate": "38.9",
        "winAverage": "1.72",
        "loseAverage": "2.0",
        "totalCount": 18,
        "winCount": 6,
        "drawCount": 5,
        "loseCount": 7,
        "getScore": 31,
        "loseScore": 36,
        "goalDifference": -5,
        "integral": 23
      },
      {
        "rank": 8,
        "teamId": "62",
        "winRate": "38.9",
        "drawRate": "11.1",
        "loseRate": "50.0",
        "winAverage": "1.56",
        "loseAverage": "2.39",
        "totalCount": 18,
        "winCount": 7,
        "drawCount": 2,
        "loseCount": 9,
        "getScore": 28,
        "loseScore": 43,
        "goalDifference": -15,
        "integral": 23
      },
      {
        "rank": 9,
        "teamId": "348",
        "winRate": "33.3",
        "drawRate": "16.7",
        "loseRate": "50.0",
        "winAverage": "1.44",
        "loseAverage": "2.06",
        "totalCount": 18,
        "winCount": 6,
        "drawCount": 3,
        "loseCount": 9,
        "getScore": 26,
        "loseScore": 37,
        "goalDifference": -11,
        "integral": 21
      },
      {
        "rank": 10,
        "teamId": "35",
        "winRate": "26.3",
        "drawRate": "31.6",
        "loseRate": "42.1",
        "winAverage": "1.05",
        "loseAverage": "1.68",
        "totalCount": 19,
        "winCount": 5,
        "drawCount": 6,
        "loseCount": 8,
        "getScore": 20,
        "loseScore": 32,
        "goalDifference": -12,
        "integral": 21
      },
      {
        "rank": 11,
        "teamId": "31",
        "winRate": "27.8",
        "drawRate": "27.8",
        "loseRate": "44.4",
        "winAverage": "0.94",
        "loseAverage": "1.72",
        "totalCount": 18,
        "winCount": 5,
        "drawCount": 5,
        "loseCount": 8,
        "getScore": 17,
        "loseScore": 31,
        "goalDifference": -14,
        "integral": 20
      },
      {
        "rank": 12,
        "teamId": "52",
        "winRate": "27.8",
        "drawRate": "22.2",
        "loseRate": "50.0",
        "winAverage": "1.33",
        "loseAverage": "1.83",
        "totalCount": 18,
        "winCount": 5,
        "drawCount": 4,
        "loseCount": 9,
        "getScore": 24,
        "loseScore": 33,
        "goalDifference": -9,
        "integral": 19
      },
      {
        "rank": 13,
        "teamId": "60",
        "winRate": "21.1",
        "drawRate": "31.6",
        "loseRate": "47.4",
        "winAverage": "1.32",
        "loseAverage": "1.84",
        "totalCount": 19,
        "winCount": 4,
        "drawCount": 6,
        "loseCount": 9,
        "getScore": 25,
        "loseScore": 35,
        "goalDifference": -10,
        "integral": 18
      },
      {
        "rank": 14,
        "teamId": "365",
        "winRate": "26.3",
        "drawRate": "10.5",
        "loseRate": "63.2",
        "winAverage": "1.42",
        "loseAverage": "1.63",
        "totalCount": 19,
        "winCount": 5,
        "drawCount": 2,
        "loseCount": 12,
        "getScore": 27,
        "loseScore": 31,
        "goalDifference": -4,
        "integral": 17
      },
      {
        "rank": 15,
        "teamId": "28",
        "winRate": "29.4",
        "drawRate": "11.8",
        "loseRate": "58.8",
        "winAverage": "1.76",
        "loseAverage": "2.06",
        "totalCount": 17,
        "winCount": 5,
        "drawCount": 2,
        "loseCount": 10,
        "getScore": 30,
        "loseScore": 35,
        "goalDifference": -5,
        "integral": 17
      },
      {
        "rank": 16,
        "teamId": "29",
        "winRate": "16.7",
        "drawRate": "33.3",
        "loseRate": "50.0",
        "winAverage": "1.11",
        "loseAverage": "1.94",
        "totalCount": 18,
        "winCount": 3,
        "drawCount": 6,
        "loseCount": 9,
        "getScore": 20,
        "loseScore": 35,
        "goalDifference": -15,
        "integral": 15
      },
      {
        "rank": 17,
        "teamId": "46",
        "winRate": "15.8",
        "drawRate": "26.3",
        "loseRate": "57.9",
        "winAverage": "1.16",
        "loseAverage": "1.84",
        "totalCount": 19,
        "winCount": 3,
        "drawCount": 5,
        "loseCount": 11,
        "getScore": 22,
        "loseScore": 35,
        "goalDifference": -13,
        "integral": 14
      },
      {
        "rank": 18,
        "teamId": "49",
        "winRate": "16.7",
        "drawRate": "22.2",
        "loseRate": "61.1",
        "winAverage": "1.11",
        "loseAverage": "2.0",
        "totalCount": 18,
        "winCount": 3,
        "drawCount": 4,
        "loseCount": 11,
        "getScore": 20,
        "loseScore": 36,
        "goalDifference": -16,
        "integral": 13
      },
      {
        "rank": 19,
        "teamId": "372",
        "winRate": "10.5",
        "drawRate": "21.1",
        "loseRate": "68.4",
        "winAverage": "1.26",
        "loseAverage": "2.53",
        "totalCount": 19,
        "winCount": 2,
        "drawCount": 4,
        "loseCount": 13,
        "getScore": 24,
        "loseScore": 48,
        "goalDifference": -24,
        "integral": 10
      },
      {
        "rank": 20,
        "teamId": "51",
        "winRate": "5.3",
        "drawRate": "15.8",
        "loseRate": "78.9",
        "winAverage": "0.84",
        "loseAverage": "2.47",
        "totalCount": 19,
        "winCount": 1,
        "drawCount": 3,
        "loseCount": 15,
        "getScore": 16,
        "loseScore": 47,
        "goalDifference": -31,
        "integral": 6
      }
    ],
    "homeHalfStandings": [
      {
        "rank": 1,
        "teamId": "26",
        "winRate": "72.2",
        "drawRate": "16.7",
        "loseRate": "11.1",
        "winAverage": "1.28",
        "loseAverage": "0.28",
        "totalCount": 18,
        "winCount": 13,
        "drawCount": 3,
        "loseCount": 2,
        "getScore": 23,
        "loseScore": 5,
        "goalDifference": 18,
        "integral": 42
      },
      {
        "rank": 2,
        "teamId": "20",
        "winRate": "61.1",
        "drawRate": "27.8",
        "loseRate": "11.1",
        "winAverage": "1.11",
        "loseAverage": "0.33",
        "totalCount": 18,
        "winCount": 11,
        "drawCount": 5,
        "loseCount": 2,
        "getScore": 20,
        "loseScore": 6,
        "goalDifference": 14,
        "integral": 38
      },
      {
        "rank": 3,
        "teamId": "19",
        "winRate": "50.0",
        "drawRate": "38.9",
        "loseRate": "11.1",
        "winAverage": "1.0",
        "loseAverage": "0.33",
        "totalCount": 18,
        "winCount": 9,
        "drawCount": 7,
        "loseCount": 2,
        "getScore": 18,
        "loseScore": 6,
        "goalDifference": 12,
        "integral": 34
      },
      {
        "rank": 4,
        "teamId": "28",
        "winRate": "42.1",
        "drawRate": "52.6",
        "loseRate": "5.3",
        "winAverage": "1.11",
        "loseAverage": "0.53",
        "totalCount": 19,
        "winCount": 8,
        "drawCount": 10,
        "loseCount": 1,
        "getScore": 21,
        "loseScore": 10,
        "goalDifference": 11,
        "integral": 34
      },
      {
        "rank": 5,
        "teamId": "24",
        "winRate": "44.4",
        "drawRate": "50.0",
        "loseRate": "5.6",
        "winAverage": "1.22",
        "loseAverage": "0.56",
        "totalCount": 18,
        "winCount": 8,
        "drawCount": 9,
        "loseCount": 1,
        "getScore": 22,
        "loseScore": 10,
        "goalDifference": 12,
        "integral": 33
      },
      {
        "rank": 6,
        "teamId": "31",
        "winRate": "36.8",
        "drawRate": "47.4",
        "loseRate": "15.8",
        "winAverage": "0.53",
        "loseAverage": "0.26",
        "totalCount": 19,
        "winCount": 7,
        "drawCount": 9,
        "loseCount": 3,
        "getScore": 10,
        "loseScore": 5,
        "goalDifference": 5,
        "integral": 30
      },
      {
        "rank": 7,
        "teamId": "62",
        "winRate": "42.1",
        "drawRate": "31.6",
        "loseRate": "26.3",
        "winAverage": "0.74",
        "loseAverage": "0.68",
        "totalCount": 19,
        "winCount": 8,
        "drawCount": 6,
        "loseCount": 5,
        "getScore": 14,
        "loseScore": 13,
        "goalDifference": 1,
        "integral": 30
      },
      {
        "rank": 8,
        "teamId": "25",
        "winRate": "38.9",
        "drawRate": "44.4",
        "loseRate": "16.7",
        "winAverage": "1.0",
        "loseAverage": "0.56",
        "totalCount": 18,
        "winCount": 7,
        "drawCount": 8,
        "loseCount": 3,
        "getScore": 18,
        "loseScore": 10,
        "goalDifference": 8,
        "integral": 29
      },
      {
        "rank": 9,
        "teamId": "35",
        "winRate": "33.3",
        "drawRate": "61.1",
        "loseRate": "5.6",
        "winAverage": "0.83",
        "loseAverage": "0.39",
        "totalCount": 18,
        "winCount": 6,
        "drawCount": 11,
        "loseCount": 1,
        "getScore": 15,
        "loseScore": 7,
        "goalDifference": 8,
        "integral": 29
      },
      {
        "rank": 10,
        "teamId": "60",
        "winRate": "41.2",
        "drawRate": "29.4",
        "loseRate": "29.4",
        "winAverage": "0.76",
        "loseAverage": "0.59",
        "totalCount": 17,
        "winCount": 7,
        "drawCount": 5,
        "loseCount": 5,
        "getScore": 13,
        "loseScore": 10,
        "goalDifference": 3,
        "integral": 26
      },
      {
        "rank": 11,
        "teamId": "29",
        "winRate": "26.3",
        "drawRate": "52.6",
        "loseRate": "21.1",
        "winAverage": "0.68",
        "loseAverage": "0.42",
        "totalCount": 19,
        "winCount": 5,
        "drawCount": 10,
        "loseCount": 4,
        "getScore": 13,
        "loseScore": 8,
        "goalDifference": 5,
        "integral": 25
      },
      {
        "rank": 12,
        "teamId": "52",
        "winRate": "36.8",
        "drawRate": "21.1",
        "loseRate": "42.1",
        "winAverage": "0.47",
        "loseAverage": "0.63",
        "totalCount": 19,
        "winCount": 7,
        "drawCount": 4,
        "loseCount": 8,
        "getScore": 9,
        "loseScore": 12,
        "goalDifference": -3,
        "integral": 25
      },
      {
        "rank": 13,
        "teamId": "33",
        "winRate": "27.8",
        "drawRate": "44.4",
        "loseRate": "27.8",
        "winAverage": "0.67",
        "loseAverage": "0.67",
        "totalCount": 18,
        "winCount": 5,
        "drawCount": 8,
        "loseCount": 5,
        "getScore": 12,
        "loseScore": 12,
        "goalDifference": 0,
        "integral": 23
      },
      {
        "rank": 14,
        "teamId": "49",
        "winRate": "21.1",
        "drawRate": "52.6",
        "loseRate": "26.3",
        "winAverage": "0.58",
        "loseAverage": "0.53",
        "totalCount": 19,
        "winCount": 4,
        "drawCount": 10,
        "loseCount": 5,
        "getScore": 11,
        "loseScore": 10,
        "goalDifference": 1,
        "integral": 22
      },
      {
        "rank": 15,
        "teamId": "348",
        "winRate": "21.1",
        "drawRate": "52.6",
        "loseRate": "26.3",
        "winAverage": "0.42",
        "loseAverage": "0.63",
        "totalCount": 19,
        "winCount": 4,
        "drawCount": 10,
        "loseCount": 5,
        "getScore": 8,
        "loseScore": 12,
        "goalDifference": -4,
        "integral": 22
      },
      {
        "rank": 16,
        "teamId": "365",
        "winRate": "16.7",
        "drawRate": "61.1",
        "loseRate": "22.2",
        "winAverage": "0.61",
        "loseAverage": "0.72",
        "totalCount": 18,
        "winCount": 3,
        "drawCount": 11,
        "loseCount": 4,
        "getScore": 11,
        "loseScore": 13,
        "goalDifference": -2,
        "integral": 20
      },
      {
        "rank": 17,
        "teamId": "27",
        "winRate": "16.7",
        "drawRate": "33.3",
        "loseRate": "50.0",
        "winAverage": "0.44",
        "loseAverage": "0.78",
        "totalCount": 18,
        "winCount": 3,
        "drawCount": 6,
        "loseCount": 9,
        "getScore": 8,
        "loseScore": 14,
        "goalDifference": -6,
        "integral": 15
      },
      {
        "rank": 18,
        "teamId": "372",
        "winRate": "16.7",
        "drawRate": "33.3",
        "loseRate": "50.0",
        "winAverage": "0.44",
        "loseAverage": "0.89",
        "totalCount": 18,
        "winCount": 3,
        "drawCount": 6,
        "loseCount": 9,
        "getScore": 8,
        "loseScore": 16,
        "goalDifference": -8,
        "integral": 15
      },
      {
        "rank": 19,
        "teamId": "51",
        "winRate": "11.1",
        "drawRate": "44.4",
        "loseRate": "44.4",
        "winAverage": "0.39",
        "loseAverage": "1.39",
        "totalCount": 18,
        "winCount": 2,
        "drawCount": 8,
        "loseCount": 8,
        "getScore": 7,
        "loseScore": 25,
        "goalDifference": -18,
        "integral": 14
      },
      {
        "rank": 20,
        "teamId": "46",
        "winRate": "16.7",
        "drawRate": "22.2",
        "loseRate": "61.1",
        "winAverage": "0.39",
        "loseAverage": "1.17",
        "totalCount": 18,
        "winCount": 3,
        "drawCount": 4,
        "loseCount": 11,
        "getScore": 7,
        "loseScore": 21,
        "goalDifference": -14,
        "integral": 13
      }
    ],
    "awayHalfStandings": [
      {
        "rank": 1,
        "teamId": "19",
        "winRate": "47.4",
        "drawRate": "42.1",
        "loseRate": "10.5",
        "winAverage": "1.21",
        "loseAverage": "0.26",
        "totalCount": 19,
        "winCount": 9,
        "drawCount": 8,
        "loseCount": 2,
        "getScore": 23,
        "loseScore": 5,
        "goalDifference": 18,
        "integral": 35
      },
      {
        "rank": 2,
        "teamId": "27",
        "winRate": "33.3",
        "drawRate": "55.6",
        "loseRate": "11.1",
        "winAverage": "0.72",
        "loseAverage": "0.5",
        "totalCount": 18,
        "winCount": 6,
        "drawCount": 10,
        "loseCount": 2,
        "getScore": 13,
        "loseScore": 9,
        "goalDifference": 4,
        "integral": 28
      },
      {
        "rank": 3,
        "teamId": "26",
        "winRate": "38.9",
        "drawRate": "33.3",
        "loseRate": "27.8",
        "winAverage": "0.83",
        "loseAverage": "0.56",
        "totalCount": 18,
        "winCount": 7,
        "drawCount": 6,
        "loseCount": 5,
        "getScore": 15,
        "loseScore": 10,
        "goalDifference": 5,
        "integral": 27
      },
      {
        "rank": 4,
        "teamId": "348",
        "winRate": "33.3",
        "drawRate": "33.3",
        "loseRate": "33.3",
        "winAverage": "0.61",
        "loseAverage": "0.78",
        "totalCount": 18,
        "winCount": 6,
        "drawCount": 6,
        "loseCount": 6,
        "getScore": 11,
        "loseScore": 14,
        "goalDifference": -3,
        "integral": 24
      },
      {
        "rank": 5,
        "teamId": "365",
        "winRate": "26.3",
        "drawRate": "42.1",
        "loseRate": "31.6",
        "winAverage": "0.53",
        "loseAverage": "0.53",
        "totalCount": 19,
        "winCount": 5,
        "drawCount": 8,
        "loseCount": 6,
        "getScore": 10,
        "loseScore": 10,
        "goalDifference": 0,
        "integral": 23
      },
      {
        "rank": 6,
        "teamId": "25",
        "winRate": "27.8",
        "drawRate": "44.4",
        "loseRate": "27.8",
        "winAverage": "0.56",
        "loseAverage": "0.56",
        "totalCount": 18,
        "winCount": 5,
        "drawCount": 8,
        "loseCount": 5,
        "getScore": 10,
        "loseScore": 10,
        "goalDifference": 0,
        "integral": 23
      },
      {
        "rank": 7,
        "teamId": "372",
        "winRate": "31.6",
        "drawRate": "26.3",
        "loseRate": "42.1",
        "winAverage": "0.58",
        "loseAverage": "0.63",
        "totalCount": 19,
        "winCount": 6,
        "drawCount": 5,
        "loseCount": 8,
        "getScore": 11,
        "loseScore": 12,
        "goalDifference": -1,
        "integral": 23
      },
      {
        "rank": 8,
        "teamId": "35",
        "winRate": "26.3",
        "drawRate": "42.1",
        "loseRate": "31.6",
        "winAverage": "0.37",
        "loseAverage": "0.63",
        "totalCount": 19,
        "winCount": 5,
        "drawCount": 8,
        "loseCount": 6,
        "getScore": 7,
        "loseScore": 12,
        "goalDifference": -5,
        "integral": 23
      },
      {
        "rank": 9,
        "teamId": "20",
        "winRate": "27.8",
        "drawRate": "38.9",
        "loseRate": "33.3",
        "winAverage": "0.83",
        "loseAverage": "0.61",
        "totalCount": 18,
        "winCount": 5,
        "drawCount": 7,
        "loseCount": 6,
        "getScore": 15,
        "loseScore": 11,
        "goalDifference": 4,
        "integral": 22
      },
      {
        "rank": 10,
        "teamId": "24",
        "winRate": "22.2",
        "drawRate": "55.6",
        "loseRate": "22.2",
        "winAverage": "0.72",
        "loseAverage": "0.72",
        "totalCount": 18,
        "winCount": 4,
        "drawCount": 10,
        "loseCount": 4,
        "getScore": 13,
        "loseScore": 13,
        "goalDifference": 0,
        "integral": 22
      },
      {
        "rank": 11,
        "teamId": "46",
        "winRate": "26.3",
        "drawRate": "31.6",
        "loseRate": "42.1",
        "winAverage": "0.58",
        "loseAverage": "0.68",
        "totalCount": 19,
        "winCount": 5,
        "drawCount": 6,
        "loseCount": 8,
        "getScore": 11,
        "loseScore": 13,
        "goalDifference": -2,
        "integral": 21
      },
      {
        "rank": 12,
        "teamId": "33",
        "winRate": "27.8",
        "drawRate": "33.3",
        "loseRate": "38.9",
        "winAverage": "0.72",
        "loseAverage": "1.0",
        "totalCount": 18,
        "winCount": 5,
        "drawCount": 6,
        "loseCount": 7,
        "getScore": 13,
        "loseScore": 18,
        "goalDifference": -5,
        "integral": 21
      },
      {
        "rank": 13,
        "teamId": "60",
        "winRate": "26.3",
        "drawRate": "31.6",
        "loseRate": "42.1",
        "winAverage": "0.53",
        "loseAverage": "0.95",
        "totalCount": 19,
        "winCount": 5,
        "drawCount": 6,
        "loseCount": 8,
        "getScore": 10,
        "loseScore": 18,
        "goalDifference": -8,
        "integral": 21
      },
      {
        "rank": 14,
        "teamId": "62",
        "winRate": "27.8",
        "drawRate": "27.8",
        "loseRate": "44.4",
        "winAverage": "0.56",
        "loseAverage": "1.06",
        "totalCount": 18,
        "winCount": 5,
        "drawCount": 5,
        "loseCount": 8,
        "getScore": 10,
        "loseScore": 19,
        "goalDifference": -9,
        "integral": 20
      },
      {
        "rank": 15,
        "teamId": "28",
        "winRate": "23.5",
        "drawRate": "41.2",
        "loseRate": "35.3",
        "winAverage": "0.76",
        "loseAverage": "0.71",
        "totalCount": 17,
        "winCount": 4,
        "drawCount": 7,
        "loseCount": 6,
        "getScore": 13,
        "loseScore": 12,
        "goalDifference": 1,
        "integral": 19
      },
      {
        "rank": 16,
        "teamId": "52",
        "winRate": "16.7",
        "drawRate": "50.0",
        "loseRate": "33.3",
        "winAverage": "0.5",
        "loseAverage": "0.89",
        "totalCount": 18,
        "winCount": 3,
        "drawCount": 9,
        "loseCount": 6,
        "getScore": 9,
        "loseScore": 16,
        "goalDifference": -7,
        "integral": 18
      },
      {
        "rank": 17,
        "teamId": "29",
        "winRate": "16.7",
        "drawRate": "44.4",
        "loseRate": "38.9",
        "winAverage": "0.39",
        "loseAverage": "0.72",
        "totalCount": 18,
        "winCount": 3,
        "drawCount": 8,
        "loseCount": 7,
        "getScore": 7,
        "loseScore": 13,
        "goalDifference": -6,
        "integral": 17
      },
      {
        "rank": 18,
        "teamId": "49",
        "winRate": "11.1",
        "drawRate": "50.0",
        "loseRate": "38.9",
        "winAverage": "0.61",
        "loseAverage": "1.17",
        "totalCount": 18,
        "winCount": 2,
        "drawCount": 9,
        "loseCount": 7,
        "getScore": 11,
        "loseScore": 21,
        "goalDifference": -10,
        "integral": 15
      },
      {
        "rank": 19,
        "teamId": "51",
        "winRate": "10.5",
        "drawRate": "42.1",
        "loseRate": "47.4",
        "winAverage": "0.37",
        "loseAverage": "0.79",
        "totalCount": 19,
        "winCount": 2,
        "drawCount": 8,
        "loseCount": 9,
        "getScore": 7,
        "loseScore": 15,
        "goalDifference": -8,
        "integral": 14
      },
      {
        "rank": 20,
        "teamId": "31",
        "winRate": "5.6",
        "drawRate": "55.6",
        "loseRate": "38.9",
        "winAverage": "0.33",
        "loseAverage": "0.94",
        "totalCount": 18,
        "winCount": 1,
        "drawCount": 10,
        "loseCount": 7,
        "getScore": 6,
        "loseScore": 17,
        "goalDifference": -11,
        "integral": 13
      }
    ],
    "leagueColorInfos": [
      {
        "color": "#FF9966",
        "leagueName": "UEFA CL qualifying",
        "beginRank": 1,
        "endRank": 4
      },
      {
        "color": "#00CCFF",
        "leagueName": "UEFA EL qualifying",
        "beginRank": 5,
        "endRank": 5
      },
      {
        "color": "#009900",
        "leagueName": "UEFA ECL qualifying",
        "beginRank": 6,
        "endRank": 6
      },
      {
        "color": "#B1A7A7",
        "leagueName": "Relegation",
        "beginRank": 18,
        "endRank": 20
      }
    ],
    "lastUpdateTime": 1715565592,
    "scoreCountType": 0,
    "conference": false
  }
}