export const SET_FIXTURES = 'SET_FIXTURES';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const CLEAR_SEARCH_TEXT = 'CLEAR_SEARCH_TEXT';
export const SET_FAVORITE_FIXTURE = 'SET_FAVORITE_FIXTURE';
export const SET_LOADING = 'SET_LOADING';

export const ADD_FILTER_VALUE = 'ADD_FILTER_VALUE';
export const REMOVE_FILTER_VALUE = 'REMOVE_FILTER_VALUE';

export const SET_EVENT_DATA = 'SET_EVENT_DATA';

export const CHANGE_ODDS_DISPLAY_TYPE = 'CHANGE_ODDS_DISPLAY_TYPE';
export const CHANGE_BOOKMAKER = 'CHANGE_BOOKMAKER';
export const SET_HANDICAP = 'SET_HANDICAP'

export const ADD_FAVORITE_TEAM = 'ADD_FAVORITE_TEAM';
export const REMOVE_FAVORITE_TEAM = 'REMOVE_FAVORITE_TEAM';
