name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Install gh-pages
        run: npm install gh-pages

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Extract repository owner
        id: extract_owner
        run: echo "::set-output name=owner::$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)"

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          REPO_OWNER: ${{ steps.extract_owner.outputs.owner }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npm run build
            npx gh-pages -d dist -b production -r https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${REPO_OWNER}/${GITHUB_REPOSITORY##*/}.git
            echo "Deploying to Production..."
            ssh -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no ec2-user@34.236.192.62 'echo "Connected to the server" && cd ~/odds-table/test-cicd && git pull && cd && rm -f index.min.js index.css && cp -r odds-table/test-cicd/assets/ assets && sudo pm2 restart server'      
            elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            npm run build
            npx gh-pages -d dist -b staging -r https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${REPO_OWNER}/${GITHUB_REPOSITORY##*/}.git
            echo "Deploying to Staging Server..."
            ssh -i ~/.ssh/aws_key.pem -o StrictHostKeyChecking=no ec2-user@34.236.192.62 'echo "Connected to the server" && cd && cd ~/odds-table/test-cicd && git pull'
          fi
          